### PR TITLE
203 - put the baseline to the last final release

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
fixes #203

**Comment by Emily-Jiang** [comment]
I have fixed the reported issue but it failed the JWT build with the error of failing to download some dependent jars for tck. It might be a temp glitch. @radcortez can you take a look?

**Comment by radcortez** [comment]
@Emily-Jiang it was just a glitch. I've rerun the build and it is ok.

**Comment by sberyozkin** [comment]
@Emily-Jiang @radcortez thanks :-)

**Pull request merged**
