### PR TITLE
Update to MP 3.3 Jakarta dependencies

### LINKED ISSUE #137: Update to Jakarta EE8 APIs for MP 4.0 in Jun 2020

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #137

### CODE REVIEW

**Comment by sberyozkin** [comment]
CC @starksm64

**Comment by radcortez** [comment]
+1

**Comment by sberyozkin** [comment]
@radcortez thanks

@rdebusscher Hi, can you please check on your own end if getting it into `JWT 1.2` works OK for you ? Looks like it can easily go into the next release.

CC @ederks85

**Comment by chunlongliang-ibm** [comment]
Is MP-JWT 1.2 for MP 3.3 or MP 4.0? what is target date for MP 3.3 and 4.0?

**Comment by rdebusscher** [comment]
@chunlongliang-ibm 

MP 3.3 is already released on March 18th.

**Comment by sberyozkin** [comment]
@rdebusscher I have a PR on my branch already to have `el-api` excluded. Thanks for the approval.
Actually I forgot to ask David, @dblevins double check please, I'll merge soon, but we can deal with any issues if any before the release

**Comment by sberyozkin** [comment]
@chunlongliang-ibm yes, originally I created this PR for MP 3.3 but since MP JWT has missed it anyway, and, as I was explained by my colleagues these dependencies are backward compatible, we may just go ahead and have them done now

**Comment by sberyozkin** [comment]
Going ahead with this merge now, lots of time to fix something if needed

**Comment by sberyozkin** [comment]
Just updated the subject of the PR to correctly refer to MP 4.0 as I'm about to link to it from the release notes

**Pull request merged**
