### PR TITLE
Checkstyle changes

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by sberyozkin** [comment]
@radcortez thanks Roberto, I can push a few exclusions to some resources where the changes look a bit unusual, please remind me how to do it `/CHECKSTYLE:OFF` and `/CHECKSTYLE:ON` or similar and I'll suggest a difference before pushing

**Comment by radcortez** [comment]
Should be good to go. Just use `// @formatter:off` and `// @formatter:on`

**Comment by sberyozkin** [comment]
Hey Roberto, thanks for your time, sorry again I did not realize that checkstyle related updates were about rebuilding with the latest parent update and committing them :-)

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
Rebased `jakarta9-branch`

**Pull request merged**
