### PR TITLE
Use MP Parent POM.

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by radcortez** [comment]
With the Parent POM Release this is now ready.

Because the Parent POM now includes the Eclipse Formatter and ImpSort, when we merge this PR, the next build will change the code style of the code, to comply with the defined rules.

**Comment by sberyozkin** [comment]
Hi Roberto @radcortez Can you please revisit this PR to align with #246 (target PR at `jakarta91-branch`) ?

**Comment by radcortez** [comment]
I think this is still valid. There is a new parent version with the Jakarta 9 dependencies. So, we could move this one forward and then update the parent version to get the new Jakarta dependencies.

**Comment by sberyozkin** [comment]
Hi @radcortez I think it can be simpler to merge from `jakarta91-branch` all the changes since we will do the parent update there anyway ?

**Comment by radcortez** [comment]
No, because the parent pom build also adds code changes due to checkstyle. They are not included here to separate both commits, but after this is one is merged we need do to a build to push the checkstyle changes. I think it will be harder to manage checkstyle changes + package changes. So my suggestions is:

- Merge this
- Submit new PR with checkstyle changes
- Include any other additional PR's if required
- Create a branch for 1.2.x or 1.x
- Update master with the jakarta rename and parent pom
- Drop the jakarta 9 branch (the work is on master)

**Comment by sberyozkin** [comment]
@radcortez OK, thanks, let me merge this one to `master`, I'd appreciate if you could follow up with a checkstyle related PR. Then I'll rebase it into the `jakarta9_branch` to continue with the #246

**Comment by sberyozkin** [comment]
Forgot to press Approved: so Approve in a comment :-)

**Pull request merged**
