### PR TITLE
Revert "Support injection for long and boolean primitive types."

### PR DESCRIPTION
**Pull request by sberyozkin**
Reverts eclipse/microprofile-jwt-auth#181

### CODE REVIEW

**Comment by sberyozkin** [comment]
@radcortez Hi Roberto, I think it needs to be rebased as the JWE server merge went yesterday,
https://github.com/eclipse/microprofile-jwt-auth/runs/585609911
is failing

**Comment by sberyozkin** [comment]
@radcortez Speaking f the rebase, is it possible to use github actions to prevent such issues in the future ?

**Comment by radcortez** [comment]
Yes you can set GH Actions to do it, but Github branch settings already have a protection for it. If you go to the project settings, in the Branch Protections Rules for `master` tick the following:

Set Require pull request reviews before merging (at least 1 reviewer)
Set Dismiss stale pull request approvals when new commits are pushed
Set Require review from Code Owners
Set Require status checks to pass before merging for the GH Actions
Set Require branches to be up to date before merging

**Comment by radcortez** [comment]
Give me a few minutes and I'll fix the commit issue.

**Comment by radcortez** [comment]
Here is the fix:
https://github.com/eclipse/microprofile-jwt-auth/pull/185

If you `Set Require branches to be up to date before merging` it should prevent this issue, unless you use you admin rights and ignore the warning on merge :)

**Comment by sberyozkin** [comment]
Hey Roberto, I never use that lightly :-), but the funny thing I don't see `Settings`

**Comment by sberyozkin** [comment]
let me close this one anyway and I'll check around

**Comment by radcortez** [comment]
Maybe you don't have permissions either :(

**Pull request closed without merging**
